name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v2
      
      # Either rename your file to index.html (recommended):
      - run: cp "latihan_jquery_yusuf hamzah taufiqurrahman.html" index.html
      
      # OR if you want to keep the original filename:
      # - run: cp "latihan_jquery_yusuf hamzah taufiqurrahman.html" index.html
      
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy
        uses: actions/deploy-pages@v2
